import {
  Html, Head, Main, NextScript,
} from 'next/document';

export default function Document() {
  return (
    <Html lang="en">
      <Head>
        <link
          href="https://fonts.googleapis.com/css2?family=Noto+Sans+TC:wght@400;700&family=Noto+Sans:wght@400;700&display=swap"
          rel="stylesheet"
        />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.7.2/animate.min.css" />
        <script src="https://cdnjs.cloudflare.com/ajax/libs/wow/1.1.2/wow.min.js" />
        <script src="https://code.jquery.com/jquery-1.12.4.min.js" />
        {/* <!--Reference the SignalR library. --> */}
        <script src="https://pi.rocket-coding.com/Scripts/jquery.signalR-2.4.3.min.js" />
        {/* <!--Reference the autoGenerated SignalR hub script. --> */}
        <script src="https://pi.rocket-coding.com/signalr/hubs" />
      </Head>
      <body>
        <Main />
        <NextScript />
      </body>
    </Html>
  );
}
