/* eslint-disable max-len */
import Head from 'next/head';
import { hasCookie } from 'cookies-next';
import { hasToken } from '@/common/redux/feature/hasToken';
import { homeComponents } from '@/lib/homeFilesRoute';
import wrapper from '@/common/redux/store';

const { Banner, SuggestCounselor, CustomTopic, PlatformFeature, UserComment, ReservationTour } = homeComponents;

export const getServerSideProps = wrapper.getServerSideProps((store) => async ({ req, res }) => {
  const passToken = hasCookie('auth', { req, res });
  if (passToken) {
    store.dispatch(hasToken(passToken));
  }
  store.dispatch(hasToken(passToken));
  return {
    props: {},
  };
});

export default function Home() {
  return (
    <>
      <Head>
        <title>11T 諮商平台建置中</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Banner />
        <CustomTopic />
        <SuggestCounselor />
        <PlatformFeature />
        <UserComment />
        <ReservationTour />
      </main>
    </>
  );
}
